// Assignment Code
var generateBtn = document.querySelector("#generate");


// Write password to the #password input
function writePassword() 
{

  // creates password variable to be the value returned by running generatePAssword 
  var password = generatePassword();
  // creates passwordText variable setting it's value to be the html element with this id password
  var passwordText = document.querySelector("#password");
  // sets the value of that html element to be the password's value, that was generated by running generatePassword
  passwordText.value = password;

  
}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
document.getElementById("generate").addEventListener("click", writePassword );

var lowerC = ["a","b","c","d","e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "y", "t", "u", "v", "w", "x", "y", "z"];
var upperC = ["A","B","C","D","E","F", "G", "H", "I","J","K","L","M","N","O","P","Q","R","S","Y","T","U","V","W","X","Y","Z"];
var spChar = ["!","@","#","$","%","^","&","*","(",")"];
var numeric = ["1","2","3","4","5","6","7","8","9","0"]
var finalPassword = ""



function generatePassword() 
{
  var emptyArray = []
 
  var charNum = prompt("What length do you want for your password? Betweeen 8 characters and 128 characters" , "");
  
  if (charNum < 8 || charNum > 128 ) 
  {
      prompt("Error. Reload.")
      console.log(emptyArray)
  }
  
var lowercase = window.confirm("Do you want your password to include lowercase?");
   
     if  (lowercase)
     {
       //add lowercase array to final array 
       emptyArray = emptyArray.concat(lowerC);
      console.log(emptyArray)
     }
     
var uppercase = window.confirm ("Do you want your password to include uppercase?");

     if (uppercase)
     {
      emptyArray = emptyArray.concat(upperC);
      console.log(emptyArray)
     }
     
var Num = window.confirm ("Do you want your password to have numeric?");
     
       if (Num)
       {
        emptyArray = emptyArray.concat(numeric);
        console.log(emptyArray)
       }
       

var specialChar = window.confirm ("Do you want your password to have special characters?")

 if (specialChar)
   {
    emptyArray = emptyArray.concat(spChar);
    console.log(emptyArray)
   }
  
    console.log(emptyArray)


   for ( i=0; i <= charNum; i++ )
   {
    var blah = Math.floor( Math.random() * emptyArray.length )
    finalPassword += emptyArray[blah] 
    console.log(blah)
   }


 // final array with generated password
   return finalPassword;


}